# Task 1: Data Collection and Data Understanding

### Download The Dataset Directly From Kaggle

In [2]:

#! kaggle datasets download -d imakash3011/customer-personality-analysis

In [3]:
import zipfile

zip_path = "customer-personality-analysis.zip"
#with zipfile.ZipFile(zip_path, "r") as zip_ref:
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall("customer_data")

print("Data Extract Successfully")

Data Extract Successfully

### Verify The Dataset Download

In [4]:
import os
print(os.listdir("customer_data"))

['marketing_campaign.csv']

### Load The Dataset

In [5]:
import pandas as pd
df = pd.read_csv("customer_data/marketing_campaign.csv", sep="\t")
print(df.shape)
df.head()

(2240, 29)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

# Task 3 Basic Dataset Inspection

### Dataset Information

In [6]:
file_path=("customer_data/marketing_campaign.csv")
file_size=os.path.getsize(file_path)
print(file_size , "in Bytes")
print("Convert Bytes to KB")

file_size_kb=file_size/1024

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Dataset Size:", round(file_size_kb, 2), "KB")
print("File Type: CSV")

220188 in Bytes
Convert Bytes to KB
Rows: 2240
Columns: 29
Dataset Size: 215.03 KB
File Type: CSV

### Check File Encoding (Optional)

In [7]:
import chardet

with open("customer_data/marketing_campaign.csv","rb") as f:
    result=chardet.detect(f.read())

print("Encoding:", result["encoding"])

Encoding: ascii

# Task 4 – Variable Inspection

In [8]:
print("--- Display Columns Name and Their Datatypes")

print(df.dtypes)

df.head()

--- Display Columns Name and Their Datatypes
ID                       int64
Year_Birth               int64
Education                  str
Marital_Status             str
Income                 float64
Kidhome                  int64
Teenhome                 int64
Dt_Customer                str
Recency                  int64
MntWines                 int64
MntFruits                int64
MntMeatProducts          int64
MntFishProducts          int64
MntSweetProducts         int64
MntGoldProds             int64
NumDealsPurchases        int64
NumWebPurchases          int64
NumCatalogPurchases      int64
NumStorePurchases        int64
NumWebVisitsMonth        int64
AcceptedCmp3             int64
AcceptedCmp4             int64
AcceptedCmp5             int64
AcceptedCmp1             int64
AcceptedCmp2             int64
Complain                 int64
Z_CostContact            int64
Z_Revenue                int64
Response                 int64
dtype: object

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

# Task 5 – Identify Missing Values

In [9]:
print("---Missing Values---")
missing_values = df.isnull().sum().sort_values(ascending=False)
print(missing_values)

---Missing Values---
Income                 24
ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

### Missing Value Percentage

In [10]:
print("---Missing Value Percentage---")
missing_percentage=(missing_values/len(df))*100
print(missing_percentage)

---Missing Value Percentage---
Income                 1.071429
ID                     0.000000
Year_Birth             0.000000
Education              0.000000
Marital_Status         0.000000
Kidhome                0.000000
Teenhome               0.000000
Dt_Customer            0.000000
Recency                0.000000
MntWines               0.000000
MntFruits              0.000000
MntMeatProducts        0.000000
MntFishProducts        0.000000
MntSweetProducts       0.000000
MntGoldProds           0.000000
NumDealsPurchases      0.000000
NumWebPurchases        0.000000
NumCatalogPurchases    0.000000
NumStorePurchases      0.000000
NumWebVisitsMonth      0.000000
AcceptedCmp3           0.000000
AcceptedCmp4           0.000000
AcceptedCmp5           0.000000
AcceptedCmp1           0.000000
AcceptedCmp2           0.000000
Complain               0.000000
Z_CostContact          0.000000
Z_Revenue              0.000000
Response               0.000000
dtype: float64

### Create a summary table

In [11]:
print("---Create a summary table---")
missing_report = pd.DataFrame({
    "Variable": missing_values.index,
    "Missing Values": missing_values.values,
    "Percentage (%)": missing_percentage.values
})
print(missing_report)

---Create a summary table---
               Variable  Missing Values  Percentage (%)
0                Income              24        1.071429
1                    ID               0        0.000000
2            Year_Birth               0        0.000000
3             Education               0        0.000000
4        Marital_Status               0        0.000000
5               Kidhome               0        0.000000
6              Teenhome               0        0.000000
7           Dt_Customer               0        0.000000
8               Recency               0        0.000000
9              MntWines               0        0.000000
10            MntFruits               0        0.000000
11      MntMeatProducts               0        0.000000
12      MntFishProducts               0        0.000000
13     MntSweetProducts               0        0.000000
14         MntGoldProds               0        0.000000
15    NumDealsPurchases               0        0.000000
16      NumWebPurchases               0        0.000000
17  NumCatalogPurchases               0        0.000000
18    NumStorePurchases               0        0.000000
19    NumWebVisitsMonth               0        0.000000
20         AcceptedCmp3               0        0.000000
21         AcceptedCmp4               0        0.000000
22         AcceptedCmp5               0        0.000000
23         AcceptedCmp1               0        0.000000
24         AcceptedCmp2               0        0.000000
25             Complain               0        0.000000
26        Z_CostContact               0        0.000000
27            Z_Revenue               0        0.000000
28             Response               0        0.000000

In [12]:
print("---Columns Only Have Missing Values---")
print(missing_report[missing_report["Missing Values"] > 0])

---Columns Only Have Missing Values---
  Variable  Missing Values  Percentage (%)
0   Income              24        1.071429

# Task 6 – Identify Duplicate Records

### Duplicate Rows
Duplicate Customer IDs (if any)

In [13]:
duplicate_rows = df.duplicated().sum()
print(f"TotalDuplicated Rows {duplicate_rows}")

duplicate_customer=df['ID'].duplicated().sum()
print(f"Total Duplicated Customer Records {duplicate_customer}")

TotalDuplicated Rows 0
Total Duplicated Customer Records 0

# Task 7 – Identify Incorrect or Inconsistent Values

### Invalid Age

In [15]:
invalid_age=df[(df['Year_Birth']<1900)|(df['Year_Birth']>2026)]
print(invalid_age)

        ID  Year_Birth Education Marital_Status   Income  Kidhome  Teenhome  \
239  11004        1893  2n Cycle         Single  60182.0        0         1
339   1150        1899       PhD       Together  83532.0        0         0

    Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  AcceptedCmp3  \
239  17-05-2014       23         8  ...                  4             0
339  26-09-2013       36       755  ...                  1             0

     AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  \
239             0             0             0             0         0
339             0             1             0             0         0

     Z_CostContact  Z_Revenue  Response
239              3         11         0
339              3         11         0

[2 rows x 29 columns]

In [16]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

### Negaive income

In [18]:
negative_income=df[(df['Income']<0)]
print(negative_income)

Empty DataFrame
Columns: [ID, Year_Birth, Education, Marital_Status, Income, Kidhome, Teenhome, Dt_Customer, Recency, MntWines, MntFruits, MntMeatProducts, MntFishProducts, MntSweetProducts, MntGoldProds, NumDealsPurchases, NumWebPurchases, NumCatalogPurchases, NumStorePurchases, NumWebVisitsMonth, AcceptedCmp3, AcceptedCmp4, AcceptedCmp5, AcceptedCmp1, AcceptedCmp2, Complain, Z_CostContact, Z_Revenue, Response]
Index: []

[0 rows x 29 columns]

### Empty Categorie

In [22]:
empty_education=df[df['Education'].astype(str).str.strip()==""]
empty_marital=df[df['Marital_Status'].astype(str).str.strip()==""]

print("--- Checking for Empty Spaces in Education Columns ---")

if len(empty_education)>0:
    print(f"Education: Yes ({len(empty_education)} empty spaces found)")
else:
    print("No Empty Columns ")


print("--- Checking for Empty Spaces in Material Columns ---")

if len(empty_marital)<0:
    print(f"Marital_Status: Yes ({len(empty_marital)} empty spaces found)")
else:
    print("No Empty Columns ")

--- Checking for Empty Spaces in Education Columns ---
No Empty Columns
--- Checking for Empty Spaces in Material Columns ---
No Empty Columns

### Incorrect dates

In [28]:
df['Dt_Customer']=pd.to_datetime(
    df['Dt_Customer'],
    format="%d-%m-%Y",
    errors='coerce'
)
invalid_dates=df[df["Dt_Customer"].isnull()]
if len(invalid_dates)>0:
    print(f"Yes Date Column have Inavlid Dates in {len(invalid_dates)}")
else:
    print("No invalid Data")

No invalid Data

### Wrong Spellings

In [39]:
print("Check Wrong Spelling")
print(df['Marital_Status'].unique())
print("NO Wrng Spelling")
# df['Marital_Status']=df['Marital_Status'].astype(str).str.capitalize()
# print("Spelling Case Standarize")

Check Wrong Spelling
<ArrowStringArray>
['Single', 'Together', 'Married', 'Divorced', 'Widow']
Length: 5, dtype: str
NO Wrng Spelling

### Unexpected values

In [40]:
print("--- Handling Unexpected Values ---")

print(df['Marital_Status'].unique())
print("No unexcepted Values")

# print("Before Removing Unexcepted Values")
# print(df['Marital_Status'].value_counts())

# df['Marital_Status']=df['Marital_Status'].replace(["Alone", "Absurd", "Yolo"], "Single")

# print("AFter Cleaning or Removing Unexceptrd Values")

# print(df['Marital_Status'].value_counts())

--- Handling Unexpected Values ---
<ArrowStringArray>
['Single', 'Together', 'Married', 'Divorced', 'Widow']
Length: 5, dtype: str
No unexcepted Values

# Task 8 – Review Numerical Variables

### Identify all numerical columns.

Examples

Income

Recency

Purchases

Product Spending

In [43]:
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numerical_cols:
    print(f"Column: {col:<20} | Type: {df[col].dtype}")

Column: ID                   | Type: int64
Column: Year_Birth           | Type: int64
Column: Income               | Type: float64
Column: Kidhome              | Type: int64
Column: Teenhome             | Type: int64
Column: Recency              | Type: int64
Column: MntWines             | Type: int64
Column: MntFruits            | Type: int64
Column: MntMeatProducts      | Type: int64
Column: MntFishProducts      | Type: int64
Column: MntSweetProducts     | Type: int64
Column: MntGoldProds         | Type: int64
Column: NumDealsPurchases    | Type: int64
Column: NumWebPurchases      | Type: int64
Column: NumCatalogPurchases  | Type: int64
Column: NumStorePurchases    | Type: int64
Column: NumWebVisitsMonth    | Type: int64
Column: AcceptedCmp3         | Type: int64
Column: AcceptedCmp4         | Type: int64
Column: AcceptedCmp5         | Type: int64
Column: AcceptedCmp1         | Type: int64
Column: AcceptedCmp2         | Type: int64
Column: Complain             | Type: int64
Column: Z_CostContact        | Type: int64
Column: Z_Revenue            | Type: int64
Column: Response             | Type: int64

# Task 9 – Review Categorical Variables

### Identify all categorical variables.

Examples

Marital Status

Campaign Response

In [46]:
cat_cols=df.select_dtypes(include=['object']).columns

for col in cat_cols:
    print(f"Column :{col:<15} | Type :{df[col].dtypes}")

Column :Education       | Type :str
Column :Marital_Status  | Type :str

C:\Users\MasterLaptops\AppData\Local\Temp\ipykernel_11868\3058603438.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols=df.select_dtypes(include=['object']).columns

# Task 10 – Business Understanding

## SUMMARY

# Task 11 – Create Initial Data Summary

In [47]:
print("--- Generating Report Stats ---")
print(f"Total Records (Rows): {df.shape[0]}")
print(f"Total Variables (Columns): {df.shape[1]}")
print(f"Numerical Columns Count: {len(df.select_dtypes(include=['int64', 'float64']).columns)}")
print(f"Categorical Columns Count: {len(df.select_dtypes(include=['object']).columns)}")
print(f"Missing Values in Income: {df['Income'].isnull().sum()}")
print(f"Duplicate Rows Count: {df.duplicated().sum()}")

--- Generating Report Stats ---
Total Records (Rows): 2240
Total Variables (Columns): 29
Numerical Columns Count: 26
Categorical Columns Count: 2
Missing Values in Income: 24

C:\Users\MasterLaptops\AppData\Local\Temp\ipykernel_11868\2107913926.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(f"Categorical Columns Count: {len(df.select_dtypes(include=['object']).columns)}")

Duplicate Rows Count: 0